local include = {};

include.npcFlags = { -- Size: 0x20 | 256 bits
	MIDGE_SEKHMET = 3,
	MAGNUS_GOLDWOOD_VILLAGE = 4,
	MAGNUS_GOLDWOOD_LANDING = 6,
	MAGNUS_SS_ANUBIS = 0,
	MAGNUS_GEM_QUARRY = 0,
	GIMLET_TAWFRET_TOWN_HALL = 0,
	GIMLET_TAWFRET_TREE = 0,
	MIDGE_SS_ANUBIS = 0,
};

include.robotMissionsFlags = { -- Size: 0x08 | byte
	GOLDWOOD = 0,
	SS_ANUBIS = 1,
	ICHOR = 2,
	ESCHEBONE = 3,
	MIZARS_PALACE = 4,
	UNUSED_5 = 5,
	UNUSED_6 = 6,
	UNUSED_7 = 7,
};

include.gameFlags = { -- Size: 0x8C | 1,120 bits
	-- these work by byte, lowest to highest bit.
	VELA = 0,
	JUNO = 1,
	LUPUS = 2,
	FLOYD = 3,
	
	INTRO_FETT_BUBB = 20,
	INTRO_LURG = 21,
	INTRO_MECHANTIDS = 22,
	INTRO_TUTORIAL = 23, 
	
	SHIPPART_POWER_CELL = 32,
	SHIPPART_RADAR_DISH = 33,
	SHIPPART_FIN = 34,
	SHIPPART_CARGO_BAY_KEY = 35,
	SHIPPART_DEFLECTOR_SHIELD = 36,
	SHIPPART_FUSE = 37,
	SHIPPART_VELAS_HATCH_KEY = 38,
	SHIPPART_JUNOS_HATCH_KEY = 39,
	SHIPPART_LUPUS_HATCH_KEY = 40,
	SHIPPART_NITROGEN_TANK = 41,
	SHIPPART_OXYGEN_TANK = 42,
	SHIPPART_STABILIZER = 43,
	
	ROBOT_COMPONENT_TOP = 44,
	ROBOT_COMPONENT_RIGHT = 45,
	ROBOT_COMPONENT_LEFT = 46,
	
	DEFEATED_FETT_BUBB = 77,
	DEFEATED_LURG = 78,
	DEFEATED_MECHANTIDS = 79,
	
	ALL_TRIBALS_RESCUED = 88,
	ACTIVATED_QUARRY_GENERATOR = 89,
	DISABLE_VELA_SELECT = 90,
	DISABLE_JUNO_SELECT = 91,
	DISABLE_LUPUS_SELECT = 92,
	
	ACTIVATED_PYRAMID = 94,
	JETPACK = 95,
};

include.flags = {
	__size = 0xB4,
	npcs = 0x00, -- u8[32]
	robotMissions = 0x20, -- u8[8]
	game = 0x28, -- u8[140]
};

return include;